import { RNG } from '@lazy-random/rng-abstract';
import { getRandomSeedAuto, ISeedLooser, XorShift } from '@bluelovers/xorshift';

/**
 * 包裝 `@bluelovers/xorshift` 的 `XorShift` 之可設定種子亂數產生器
 * (Seedable Random Number Generator)：狀態推進與取樣全部委託 (Delegate) 底層實例，
 * 本類別只負責種子 (Seed) 正規化與生命週期管理。
 *
 * A seedable random number generator wrapping `XorShift` from `@bluelovers/xorshift`:
 * state advance and sampling are fully delegated to the underlying instance, while
 * this class only handles seed normalization and lifecycle management.
 */
export class RNGXorShift128 extends RNG
{
	/**
	 * 底層亂數來源 (Underlying Random Source)：由 `_init()` 依正規化後的種子建立，
	 * `seed()` 與 `next()` 皆透過它操作狀態。
	 *
	 * The underlying random source, created by `_init()` from the normalized seed;
	 * both `seed()` and `next()` work through it.
	 */
	protected _rng: XorShift

	/**
	 * 建立 xorshift128 亂數產生器。
	 * Create an xorshift128 random number generator.
	 *
	 * @param seed 種子 (Seed)，可省略；省略時由 `getRandomSeedAuto()` 自動產生 / the seed, may be omitted; auto-generated by `getRandomSeedAuto()` when omitted
	 * @param opts 選項 (Options)，轉交 `_init()` 與基類 / options, forwarded to `_init()` and the base class
	 * @param argv 其餘參數，原樣轉交 `_init()` / the remaining arguments, forwarded to `_init()`
	 */
	constructor(seed?: ISeedLooser, opts?, ...argv)
	{
		super()

		this._init(seed, opts, ...argv)
	}

	/**
	 * 初始化 (Initialize) 基類狀態、正規化種子並建立底層 `XorShift` 實例。
	 * Initialize the base class state, normalize the seed and create the underlying `XorShift` instance.
	 *
	 * @param seed 種子 (Seed)，`null`／`undefined` 時自動補隨機種子 / the seed; a random seed is substituted for `null`／`undefined`
	 * @param opts 選項 (Options)，轉交基類 / options, forwarded to the base class
	 * @param argv 其餘參數，轉交基類 / the remaining arguments, forwarded to the base class
	 */
	protected override _init(seed: ISeedLooser, opts?, ...argv)
	{
		/**
		 * 依序完成三件事：先讓基類記帳 (Bookkeeping) 完成，再把種子交給
		 * `getRandomSeedAuto()` 正規化（含自動補值），最後以正規化結果建立
		 * 底層 `XorShift`，確保每次初始化都拿到可用的亂數來源。
		 *
		 * Three steps in order: let the base class finish its bookkeeping first,
		 * normalize the seed via `getRandomSeedAuto()` (which also substitutes a value
		 * when missing), then create the underlying `XorShift` from the normalized seed,
		 * guaranteeing a usable random source after every initialization.
		 */
		super._init(seed, opts, ...argv);
		seed = getRandomSeedAuto(seed);
		this._rng = new XorShift(seed);
	}

	/**
	 * 重新播种 (Reseed)：以新種子重設底層 `XorShift` 狀態。
	 * Reseed: reset the underlying `XorShift` state with a new seed.
	 *
	 * @param seed 種子 (Seed)，`null`／`undefined` 時自動補隨機種子 / the seed; a random seed is substituted for `null`／`undefined`
	 * @param opts 選項 (Options)，本實作未使用 / options; unused in this implementation
	 * @param argv 其餘參數，本實作未使用 / the remaining arguments; unused in this implementation
	 */
	override seed(seed?: ISeedLooser, opts?, ...argv)
	{
		/**
		 * 只在 `null`／`undefined` 時補隨機種子（Nullish Coalescing）：與 `||` 不同，
		 * `0`、`''` 等 falsy 但合法的種子會被保留，避免重新播种時意外丟失呼叫者指定的種子。
		 *
		 * Substitute a random seed only for `null`／`undefined` (nullish coalescing): unlike
		 * `||`, falsy but legitimate seeds such as `0` or `''` are preserved, so an
		 * explicit seed given by the caller is not accidentally lost on reseed.
		 */
		seed ??= getRandomSeedAuto();
		this._rng.seed(seed);
	}

	/**
	 * 取下一個亂數 (Random Number)，直接委託 (Delegate) 底層 `XorShift.random()`。
	 * Get the next random number, delegating directly to the underlying `XorShift.random()`.
	 *
	 * @returns 底層 `XorShift.random()` 的回傳值 / the value returned by the underlying `XorShift.random()`
	 */
	next()
	{
		return this._rng.random()
	}

	/**
	 * 固定回傳 `true`，標示此產生器可設定種子 (Seedable)，基類允許呼叫 `seed()`。
	 * Always returns `true`, marking this generator as seedable so the base class allows `seed()` calls.
	 */
	public override get seedable()
	{
		return true
	}

	/**
	 * 產生器名稱 (Generator Name)，供除錯或辨識演算法時使用。
	 * The generator name, used for debugging or algorithm identification.
	 *
	 * @returns 固定字串 `'xorshift128'` / the constant string `'xorshift128'`
	 */
	override get name()
	{
		return 'xorshift128'
	}
}

export default RNGXorShift128
