import RNGSeedRandom from './generators/seedrandom';
import RNG from './rng';
import RNGXOR128 from './generators/xor128';
import RNGFunction, { IRNGFunctionSeed } from './generators/function';
import RNGMathRandom from './generators/math-random';
export declare type IRNGFactoryType = 'xor128' | 'function' | 'function' | 'default' | 'seedrandom' | RNG | IRNGFunctionSeed | any;
export declare function RNGFactory(): RNGFunction;
export declare function RNGFactory<R extends RNG>(arg0: R, ...rest: any[]): R;
export declare function RNGFactory(arg0: 'xor128', ...rest: any[]): RNGXOR128;
export declare function RNGFactory(arg0: 'function', ...rest: any[]): RNGFunction;
export declare function RNGFactory<S extends IRNGFunctionSeed = IRNGFunctionSeed>(arg0: 'function', ...rest: any[]): RNGFunction<S>;
export declare function RNGFactory(arg0: 'default', ...rest: any[]): RNGMathRandom;
export declare function RNGFactory(arg0: 'seedrandom', ...rest: any[]): RNGSeedRandom;
export declare function RNGFactory<S extends IRNGFunctionSeed = IRNGFunctionSeed>(arg0: S, ...rest: any[]): RNGFunction<S>;
export declare function RNGFactory<R extends RNG = RNG>(...argv: any[]): R;
export default RNGFactory;
