"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.arrayFill = exports.uuidv4 = exports.sumInt = exports.sumFloat = exports.charID = exports.itemByWeightUnique = exports.itemByWeight = exports.arrayUnique = exports.arrayShuffle = exports.arrayIndex = exports.bytes = exports.byte = exports.uniformInt = exports.uniformBoolean = exports.uniform = exports.poisson = exports.dfPareto = exports.dfNormal = exports.dfLogNormal = exports.dfIrwinHall = exports.dfGeometric = exports.dfExponential = exports.dfBinomial = exports.dfBernoulli = exports.dfBates = void 0;
const df_algorithm_1 = require("@lazy-random/df-algorithm");
Object.defineProperty(exports, "dfBates", { enumerable: true, get: function () { return df_algorithm_1.dfBates; } });
Object.defineProperty(exports, "dfBernoulli", { enumerable: true, get: function () { return df_algorithm_1.dfBernoulli; } });
Object.defineProperty(exports, "dfBinomial", { enumerable: true, get: function () { return df_algorithm_1.dfBinomial; } });
Object.defineProperty(exports, "dfExponential", { enumerable: true, get: function () { return df_algorithm_1.dfExponential; } });
Object.defineProperty(exports, "dfGeometric", { enumerable: true, get: function () { return df_algorithm_1.dfGeometric; } });
Object.defineProperty(exports, "dfIrwinHall", { enumerable: true, get: function () { return df_algorithm_1.dfIrwinHall; } });
Object.defineProperty(exports, "dfLogNormal", { enumerable: true, get: function () { return df_algorithm_1.dfLogNormal; } });
Object.defineProperty(exports, "dfNormal", { enumerable: true, get: function () { return df_algorithm_1.dfNormal; } });
Object.defineProperty(exports, "dfPareto", { enumerable: true, get: function () { return df_algorithm_1.dfPareto; } });
const poisson_1 = __importDefault(require("./distributions/poisson"));
exports.poisson = poisson_1.default;
const df_uniform_1 = require("@lazy-random/df-uniform");
Object.defineProperty(exports, "uniform", { enumerable: true, get: function () { return df_uniform_1.uniformFloat; } });
Object.defineProperty(exports, "uniformInt", { enumerable: true, get: function () { return df_uniform_1.uniformInt; } });
Object.defineProperty(exports, "uniformBoolean", { enumerable: true, get: function () { return df_uniform_1.uniformBoolean; } });
Object.defineProperty(exports, "byte", { enumerable: true, get: function () { return df_uniform_1.uniformByte; } });
Object.defineProperty(exports, "bytes", { enumerable: true, get: function () { return df_uniform_1.uniformBytes; } });
const char_id_1 = __importDefault(require("./distributions/char-id"));
exports.charID = char_id_1.default;
const df_item_by_weight_1 = require("@lazy-random/df-item-by-weight");
Object.defineProperty(exports, "itemByWeight", { enumerable: true, get: function () { return df_item_by_weight_1.itemByWeight; } });
Object.defineProperty(exports, "itemByWeightUnique", { enumerable: true, get: function () { return df_item_by_weight_1.itemByWeightUnique; } });
const sum_float_1 = __importDefault(require("./distributions/sum-float"));
exports.sumFloat = sum_float_1.default;
const sum_int_1 = __importDefault(require("./distributions/sum-int"));
exports.sumInt = sum_int_1.default;
const uuidv4_1 = __importDefault(require("./distributions/uuidv4"));
exports.uuidv4 = uuidv4_1.default;
const df_array_1 = require("@lazy-random/df-array");
Object.defineProperty(exports, "arrayFill", { enumerable: true, get: function () { return df_array_1.arrayFill; } });
Object.defineProperty(exports, "arrayIndex", { enumerable: true, get: function () { return df_array_1.arrayIndex; } });
Object.defineProperty(exports, "arrayShuffle", { enumerable: true, get: function () { return df_array_1.arrayShuffle; } });
Object.defineProperty(exports, "arrayUnique", { enumerable: true, get: function () { return df_array_1.arrayUnique; } });
exports.default = exports;
//# sourceMappingURL=distributions.js.map