"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.arrayFill = exports.uuidv4 = exports.sumInt = exports.sumFloat = exports.charID = exports.itemByWeightUnique = exports.itemByWeight = exports.arrayUnique = exports.arrayShuffle = exports.arrayIndex = exports.bytes = exports.byte = exports.uniformInt = exports.uniformBoolean = exports.uniform = exports.poisson = exports.pareto = exports.normal = exports.logNormal = exports.irwinHall = exports.geometric = exports.exponential = exports.binomial = exports.bernoulli = exports.bates = void 0;
const bates_1 = __importDefault(require("./distributions/bates"));
exports.bates = bates_1.default;
const bernoulli_1 = __importDefault(require("./distributions/bernoulli"));
exports.bernoulli = bernoulli_1.default;
const binomial_1 = __importDefault(require("./distributions/binomial"));
exports.binomial = binomial_1.default;
const exponential_1 = __importDefault(require("./distributions/exponential"));
exports.exponential = exponential_1.default;
const geometric_1 = __importDefault(require("./distributions/geometric"));
exports.geometric = geometric_1.default;
const irwin_hall_1 = __importDefault(require("./distributions/irwin-hall"));
exports.irwinHall = irwin_hall_1.default;
const log_normal_1 = __importDefault(require("./distributions/log-normal"));
exports.logNormal = log_normal_1.default;
const normal_1 = __importDefault(require("./distributions/normal"));
exports.normal = normal_1.default;
const pareto_1 = __importDefault(require("./distributions/pareto"));
exports.pareto = pareto_1.default;
const poisson_1 = __importDefault(require("./distributions/poisson"));
exports.poisson = poisson_1.default;
const df_uniform_1 = require("@lazy-random/df-uniform");
Object.defineProperty(exports, "uniform", { enumerable: true, get: function () { return df_uniform_1.uniformFloat; } });
Object.defineProperty(exports, "uniformInt", { enumerable: true, get: function () { return df_uniform_1.uniformInt; } });
Object.defineProperty(exports, "uniformBoolean", { enumerable: true, get: function () { return df_uniform_1.uniformBoolean; } });
Object.defineProperty(exports, "byte", { enumerable: true, get: function () { return df_uniform_1.uniformByte; } });
Object.defineProperty(exports, "bytes", { enumerable: true, get: function () { return df_uniform_1.uniformBytes; } });
const array_index_1 = __importDefault(require("./distributions/array-index"));
exports.arrayIndex = array_index_1.default;
const array_shuffle_1 = __importDefault(require("./distributions/array-shuffle"));
exports.arrayShuffle = array_shuffle_1.default;
const array_unique_1 = __importDefault(require("./distributions/array-unique"));
exports.arrayUnique = array_unique_1.default;
const char_id_1 = __importDefault(require("./distributions/char-id"));
exports.charID = char_id_1.default;
const item_by_weight_1 = __importDefault(require("./distributions/item-by-weight"));
exports.itemByWeight = item_by_weight_1.default;
const item_by_weight_unique_1 = __importDefault(require("./distributions/item-by-weight-unique"));
exports.itemByWeightUnique = item_by_weight_unique_1.default;
const sum_float_1 = __importDefault(require("./distributions/sum-float"));
exports.sumFloat = sum_float_1.default;
const sum_int_1 = __importDefault(require("./distributions/sum-int"));
exports.sumInt = sum_int_1.default;
const uuidv4_1 = __importDefault(require("./distributions/uuidv4"));
exports.uuidv4 = uuidv4_1.default;
const array_fill_1 = __importDefault(require("./distributions/array-fill"));
exports.arrayFill = array_fill_1.default;
exports.default = exports;
//# sourceMappingURL=distributions.js.map